<?php
require_once __DIR__ . '/../backend/middleware/RoleMiddleware.php'; require_once __DIR__ . '/../backend/services/PersonnelDataService.php';
$roleMiddleware = new RoleMiddleware(); $roleMiddleware->requireRole('staff'); $service = new PersonnelDataService(new Database());
$farmerCount = count($service->farmers()); $livestockCount = count($service->recent('livestock', 50)); $catchCount = count($service->recent('fish_catch', 50)); $priceCount = count($service->recent('price_monitoring', 50));
$prices = $service->recent('price_monitoring', 50); $products = [];
foreach ($service->products() as $product) { $products[(int) $product['id']] = $product['name']; }
$pageTitle = 'Personnel Reports - Municipal Agriculture Office Jimenez'; $pageDescription = 'Personnel monitoring reports.'; $assetBase = 'assets'; $activePage = 'reports'; require_once __DIR__ . '/../frontend/components/header.php'; require_once __DIR__ . '/../frontend/components/personnel-nav.php';
?>
<main class="min-h-screen bg-surface-container-low"><section class="max-w-container-max mx-auto px-gutter-mobile lg:px-gutter-desktop py-space-xl"><p class="text-xs uppercase tracking-wider text-primary font-bold">Monitoring reports</p><h1 class="text-3xl font-extrabold mt-2">Personnel reports</h1><p class="text-sm text-on-surface-variant mt-2 mb-space-lg">A current summary of data entered by personnel.</p><div class="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-space-lg"><div class="bg-surface-container-lowest border border-surface-container rounded-lg p-5"><p class="text-xs uppercase text-on-surface-variant">Farmers</p><p class="text-3xl font-extrabold text-primary mt-2"><?= $farmerCount ?></p></div><div class="bg-surface-container-lowest border border-surface-container rounded-lg p-5"><p class="text-xs uppercase text-on-surface-variant">Livestock records</p><p class="text-3xl font-extrabold text-primary mt-2"><?= $livestockCount ?></p></div><div class="bg-surface-container-lowest border border-surface-container rounded-lg p-5"><p class="text-xs uppercase text-on-surface-variant">Fish catch</p><p class="text-3xl font-extrabold text-primary mt-2"><?= $catchCount ?></p></div><div class="bg-surface-container-lowest border border-surface-container rounded-lg p-5"><p class="text-xs uppercase text-on-surface-variant">Price entries</p><p class="text-3xl font-extrabold text-primary mt-2"><?= $priceCount ?></p></div></div><div class="bg-surface-container-lowest border border-surface-container rounded-lg overflow-hidden"><div class="p-space-lg border-b border-surface-container"><h2 class="text-xl font-bold">Price monitoring report</h2><p class="text-sm text-on-surface-variant mt-1">Latest recorded prices for vegetables and staple products.</p></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-surface-container-low text-xs uppercase"><tr><th class="p-3">Date</th><th class="p-3">Product</th><th class="p-3">Min</th><th class="p-3">Max</th><th class="p-3">Average</th><th class="p-3">Location</th></tr></thead><tbody><?php foreach ($prices as $price): ?><tr class="border-t border-surface-container"><td class="p-3"><?= htmlspecialchars($price['recorded_date']) ?></td><td class="p-3 font-semibold"><?= htmlspecialchars($products[(int) $price['product_id']] ?? 'Product #' . $price['product_id']) ?></td><td class="p-3">PHP <?= number_format((float) ($price['minimum_price'] ?? 0), 2) ?></td><td class="p-3">PHP <?= number_format((float) ($price['maximum_price'] ?? 0), 2) ?></td><td class="p-3 font-bold text-primary">PHP <?= number_format((float) $price['average_price'], 2) ?></td><td class="p-3"><?= htmlspecialchars($price['location'] ?? '-') ?></td></tr><?php endforeach; ?></tbody></table></div></div></section></main><?php require_once __DIR__ . '/../frontend/components/footer.php'; ?>
