CREATE TABLE IF NOT EXISTS fish_catch (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	fisherman_id BIGINT UNSIGNED NOT NULL,
	boat_id BIGINT UNSIGNED NULL,
	species_id BIGINT UNSIGNED NOT NULL,
	gear_id BIGINT UNSIGNED NULL,
	catch_date DATE NOT NULL,
	landing_site VARCHAR(150) NULL,
	quantity DECIMAL(12,2) NOT NULL,
	unit VARCHAR(30) NOT NULL DEFAULT 'kg',
	estimated_value DECIMAL(12,2) NULL,
	notes TEXT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	KEY idx_fish_catch_fisherman (fisherman_id),
	KEY idx_fish_catch_boat (boat_id),
	KEY idx_fish_catch_species (species_id),
	KEY idx_fish_catch_date (catch_date),
	CONSTRAINT fk_fish_catch_fisherman FOREIGN KEY (fisherman_id) REFERENCES fishermen (id) ON DELETE RESTRICT,
	CONSTRAINT fk_fish_catch_boat FOREIGN KEY (boat_id) REFERENCES boats (id) ON DELETE SET NULL,
	CONSTRAINT fk_fish_catch_species FOREIGN KEY (species_id) REFERENCES fish_species (id) ON DELETE RESTRICT,
	CONSTRAINT fk_fish_catch_gear FOREIGN KEY (gear_id) REFERENCES fishing_gears (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
