ALTER TABLE fishermen
    ADD COLUMN rsbsa_number VARCHAR(80) NULL AFTER user_id;

CREATE TABLE IF NOT EXISTS fishery_applications (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    fisherman_id BIGINT UNSIGNED NULL,
    applicant_last_name VARCHAR(100) NOT NULL,
    applicant_first_name VARCHAR(100) NOT NULL,
    applicant_middle_name VARCHAR(100) NULL,
    fishermen_association VARCHAR(200) NULL,
    address VARCHAR(255) NULL,
    spouse_name VARCHAR(200) NULL,
    contact_number VARCHAR(30) NULL,
    sex ENUM('male', 'female', 'other') NULL,
    civil_status VARCHAR(30) NULL,
    beneficiary_name VARCHAR(200) NULL,
    beneficiary_relation VARCHAR(100) NULL,
    boat_type VARCHAR(100) NULL,
    boat_material VARCHAR(100) NULL,
    motor_number VARCHAR(100) NULL,
    chassis_number VARCHAR(100) NULL,
    usage_description VARCHAR(255) NULL,
    length_meters DECIMAL(8,2) NULL,
    breadth_meters DECIMAL(8,2) NULL,
    depth_meters DECIMAL(8,2) NULL,
    gross_tonnage DECIMAL(10,2) NULL,
    boat_age_years DECIMAL(6,2) NULL,
    boat_color VARCHAR(80) NULL,
    registration_number VARCHAR(80) NULL,
    or_number VARCHAR(80) NULL,
    or_date DATE NULL,
    location_of_property VARCHAR(255) NULL,
    desired_sum_insured DECIMAL(14,2) NULL,
    cover_from DATE NULL,
    cover_to DATE NULL,
    mortgage_to VARCHAR(200) NULL,
    mortgage_branch VARCHAR(150) NULL,
    mortgage_address VARCHAR(255) NULL,
    status ENUM('draft', 'submitted', 'reviewed') NOT NULL DEFAULT 'submitted',
    reviewed_by VARCHAR(150) NULL,
    application_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_fishery_applications_fisherman (fisherman_id),
    KEY idx_fishery_applications_status (status),
    CONSTRAINT fk_fishery_applications_fisherman FOREIGN KEY (fisherman_id) REFERENCES fishermen (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;